home/urls.py
from django.urls import path

from . import views
app_name = 'home'
urlpatterns = [
    path('', views.index, name='index'),
]

main_app/urls.py
from django.urls import path, include
from django.contrib import admin

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('story_1/', include('story_1.urls')),
    path('story_4/', include('story_4.urls')),
    path('story_5/', include('story_5.urls')),
    path('story_6/', include('story_6.urls')),
    path('story_7/', include('story_7.urls')),
    path('story_8/', include('story_8.urls')),
    path('story_9/', include('story_9.urls')),
]

story_1/urls.py
from django.urls import path

from . import views
app_name = 'story_1'
urlpatterns = [
    path('', views.index, name='index'),
]

story_4/urls.py
from django.urls import path

from . import views
app_name = 'story_4'
urlpatterns = [
    path('', views.index, name='index'),
    path('contact/', views.contact, name='contact'),
]

story_5/urls.py
from django.urls import path
from . import views

app_name = 'story_5'
urlpatterns = [
    path('', views.index, name='index'),
    path('create_matkul', views.create_course, name="create_course"),
    path('<int:id>', views.course_detail, name="course_detail"),
    path('view-matkul/<int:id>/delete', views.delete_course, name="delete_course"),
    
]

story_6/urls.py
from django.urls import path
from . import views

app_name = 'story_6'

urlpatterns = [
    path('', views.index, name="index"),
    path('register/', views.register, name="register")
]

story_7/urls.py
from django.urls import path
from . import views

app_name = 'story_7'

urlpatterns = [
    path('', views.index, name="index"),
]

story_8/urls.py
from django.urls import path
from . import views

app_name = 'story_8'

urlpatterns = [
    path('', views.index, name="index"),
    path('api', views.search, name="api"),
]

story_9/urls.py
from django.urls import path
from . import views

app_name = 'story_9'

urlpatterns = [
    path('', views.index, name="index"),
]

home/models.py
from django.db import models

# Create your models here.

story_1/models.py
from django.db import models

# Create your models here.

story_4/models.py
from django.db import models

# Create your models here.

story_5/models.py
from django.db import models

# Create your models here.

class Semester(models.Model):
    term_choices = [
        ('Ganjil','Ganjil'),
        ('Genap','Genap')
    ]
    term_choices = models.CharField(max_length=6, choices=term_choices, default= 'Ganjil')
    year = models.CharField(max_length=9)

    def __str__(self):
        return f'{self.year} {self.term_choices}'

class MataKuliah(models.Model):
    nama = models.CharField(max_length=100)
    sks = models.PositiveSmallIntegerField()
    dosen = models.CharField(max_length=100)
    kelas = models.CharField(max_length=50)
    semester = models.ForeignKey("Semester", on_delete=models.CASCADE)
    deskripsi = models.TextField()

    def __str__(self):
        return self.nama

story_6/models.py
from django.db import models


class Activities(models.Model):
    activities_name = models.CharField(max_length=100)
    def __str__(self):
        return self.activities_name


class People(models.Model):
    people_name = models.CharField(max_length=100)
    activities = models.ForeignKey(Activities, on_delete=models.CASCADE)
    def __str__(self):
        return self.people_name

story_7/models.py
from django.db import models

# Create your models here.

story_5/forms.py
from django.db.models import fields
from django.forms import ModelForm
from .models import MataKuliah

# Form Class
class MataKuliahForm(ModelForm):
    class Meta:
        model = MataKuliah
        fields = ['nama','sks','dosen','kelas','semester','deskripsi']

story_6/forms.py
from django.db.models import fields
from django.forms import ModelForm
from .models import People


class PeopleForm(ModelForm):
    class Meta:
        model = People
        fields = ['people_name', 'activities']

story_9/forms.py
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm

class CreateUserForm(UserCreationForm):
    def __init__(self, *args, **kwargs):
        super(CreateUserForm, self).__init__(*args, **kwargs)

        for fieldname in ['username', 'password1', 'password2']:
            self.fields[fieldname].help_text = None

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

home/views.py
from django.shortcuts import render

def index(request):
    return render(request,"home/index.html")

story_1/views.py
from django.http import response
from django.shortcuts import render

# Create your views here.


def index(request):
    return render(request,"story_1/index.html")

story_4/views.py
from django.shortcuts import render

# Create your views here.


def index(request):
    return render(request, "story_4/index.html")


def contact(request):
    return render(request, "story_4/contact.html")

story_5/views.py
from django.http import request
from django.shortcuts import redirect, render
from .forms import MataKuliahForm
from .models import MataKuliah

# Create your views here.


def index(request):
    mata_kuliah = MataKuliah.objects.all()
    context = {'page_title': 'Story 5', 'mata_kuliah': mata_kuliah}
    return render(request, "story_5/index.html", context)


def create_course(request):
    form = MataKuliahForm(request.POST or None)
    if (form.is_valid() and request.method == 'POST'):
        form.save()
        return redirect('story_5:index')
    context = {'page_title': "Create Course", 'form': form}
    return render(request, 'story_5/create_course.html', context)


def course_detail(request, id):
    mata_kuliah = MataKuliah.objects.get(id=id)
    context = {'page_title': mata_kuliah.nama, 'mata_kuliah': mata_kuliah}
    return render(request, 'story_5/course_detail.html', context)


def delete_course(request, id):
    mata_kuliah = MataKuliah.objects.get(id=id)
    mata_kuliah.delete()
    return redirect('story_5:index')

story_6/views.py
from django.http import request
from django.shortcuts import redirect, render
from .forms import PeopleForm
from .models import People, Activities


def index(request):
    people = People.objects.all()
    activities = Activities.objects.all()
    context = {'people': people, 'activities': activities, 'page_title' : 'Activities'}
    return render(request, 'story_6/index.html', context)


def register(request):
    form = PeopleForm(request.POST or None)
    if (form.is_valid() and request.method == 'POST'):
        form.save()
        return redirect('story_6:index')
    context = {'page_title': 'register', 'form':form}
    return render(request, "story_6/register.html", context)

story_7/views.py
from django.http import request
from django.shortcuts import render


def index(request):
    context = {'page_title' : 'Activities'}
    return render(request, 'story_7/index.html', context)

story_8/views.py
from django.http import JsonResponse
from django.http import response
from django.shortcuts import render
import urllib3
from json import loads


def index(request):
    context = {'page_title': 'API'}
    return render(request, 'story_8/index.html', context)


def search(request):
    http = urllib3.PoolManager()
    response = http.request(
        'GET', "https://www.googleapis.com/books/v1/volumes?" +request.GET.urlencode())
    context = loads(response.data.decode('utf-8'))

    return JsonResponse(context)

story_9/views.py
from django.http import response
from django.shortcuts import render, redirect
from .forms import CreateUserForm
from django.contrib.auth import authenticate, login


def index(request):
    form = CreateUserForm()
    message = "Create your account"
    if request.method == "POST":
        form = CreateUserForm(request.POST)
        if form.is_valid():
            form.save()
            user = authenticate(username=form.cleaned_data.get("username"),
            password=form.cleaned_data.get("password1"))
            login(request, user)
        else:
            message = "⚠️failed to create account"
            form = CreateUserForm()
    context = {'page_title': 'Login', 'form' : form, 'message':message}
    return render(request, 'story_9/index.html', context)

story_5/templates/story_5/base.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@200;300;400;500;600;700&display=swap"
    rel="stylesheet" />
  <link rel="stylesheet" href="{% static 'story_5/style.css' %}" />
  <link rel="stylesheet" href="{% static 'home/nav.css' %}" />
  <title>{{ page_title }}</title>
</head>

<body>
  {% include "home/nav.html" %}
  <div class="content">
    {% block content %}
      replace me
    {% endblock %}
  </div>

</body>

</html>

story_5/templates/story_5/course_detail.html
{% extends 'story_5/base.html' %}
{% block content  %}
<h1>Mata Kuliah {{ mata_kuliah.nama }}</h1>
<div>
  <div>
    <table width=100%>
      <tr>
        <th>SKS</th>
        <th>: {{ mata_kuliah.sks }}</th>
      </tr>
      <tr>
        <th>Kelas</th>
        <th>: {{ mata_kuliah.kelas }}</th>
      </tr>
      <tr>
        <th>Dosen</th>
        <th>: {{ mata_kuliah.dosen }}</th>
      </tr>
      <tr>
        <th>Semester</th>
        <th>: {{ mata_kuliah.semester }}</th>
      </tr>
    </table>
    <div class="description">
      <h3>Deskripsi</h3>
      <p>{{ mata_kuliah.deskripsi }}</p>
    </div>
    <a class="btn btn-delete" href="{% url 'story_5:delete_course' mata_kuliah.id %}" >Delete</a>
  </div>

</div>
{% endblock  %}

story_5/templates/story_5/create_course.html
{% extends 'story_5/base.html' %}
{% block content  %}

<br>
<h1> Create new Course </h1>
<br>
<div>
  <form method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <input class="btn" type="submit" value="Submit" />
  </form>
</div>



{% endblock  %}

story_5/templates/story_5/index.html
{% extends 'story_5/base.html' %}

{% block content  %}
<h1>Mata Kuliah</h1>
<div class="space">
  <a class="btn" href="{% url 'story_5:create_course' %}">Add Course</a>
</div>
{% if mata_kuliah  %}
<div class="grid">
  {% for i in mata_kuliah %}
  <div class="card child">
    <div class="align-center">
      <h5 class="card-title">{{ i.nama }}</h5>
      <p class="card-text">Kelas : {{ i.kelas }}</p>
      <p class="card-text">Dosen : {{ i.dosen }}</p>
      <a href="{% url 'story_5:course_detail' id=i.id %}" class="btn">Details</a>
    </div>
  </div>
  {% endfor %}
</div>
{% else %}
<h3>Add matkul to see what it can do</h3>
{% endif %}

{% endblock  %}

story_6/templates/story_6/base.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@200;300;400;500;600;700&display=swap"
    rel="stylesheet" />
  <link rel="stylesheet" href="{% static 'story_6/style.css' %}" />
  <link rel="stylesheet" href="{% static 'home/nav.css' %}" />
  <title>{{ page_title }}</title>
</head>

<body>
  {% include "home/nav.html" %}
  <div class="content">
    {% block content %}
      replace me
    {% endblock %}
  </div>

</body>

</html>

story_6/templates/story_6/index.html
{% extends 'story_6/base.html' %}

{% block content  %}
<h1>Activities</h1>
<div class="space">
  <a class="btn" href="{% url 'story_6:register' %}">Add Person</a>
</div>
{% if activities  %}
<div class="grid">
  {% for i in activities %}
  <div class="card child">
    <div class="align-center">
      <h5 class="card-title">{{ i.activities_name }}</h5>
      <p class="card-text">Registered Person</p>
      {% for j in people %}
        {% if j.activities.activities_name == i.activities_name %}
          <p class="card-text">{{ j.people_name }}</p>
        {% endif %}
      {% endfor %}
    </div>
  </div>
  {% endfor %}
</div>
{% else %}
<h3>Ask admin to add activities</h3>
{% endif %}

{% endblock  %}

story_6/templates/story_6/register.html
{% extends 'story_6/base.html' %}
{% block content  %}
<br>
<h1> Register </h1>
<br>
<div>
  <form method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <input class="btn" type="submit" value="Submit" />
  </form>
</div>
{% endblock  %}