home/urls.py
from django.urls import path

from . import views
app_name = 'home'
urlpatterns = [
    path('', views.index, name='index'),
]

main_app/urls.py
from django.urls import path, include
from django.contrib import admin

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('story_1/', include('story_1.urls')),
    path('story_4/', include('story_4.urls')),
    path('story_5/', include('story_5.urls')),
    path('story_6/', include('story_6.urls')),
    path('story_7/', include('story_7.urls')),
    path('story_8/', include('story_8.urls')),
    path('story_9/', include('story_9.urls')),
]

story_1/urls.py
from django.urls import path

from . import views
app_name = 'story_1'
urlpatterns = [
    path('', views.index, name='index'),
]

story_4/urls.py
from django.urls import path

from . import views
app_name = 'story_4'
urlpatterns = [
    path('', views.index, name='index'),
    path('contact/', views.contact, name='contact'),
]

story_5/urls.py
from django.urls import path
from . import views

app_name = 'story_5'
urlpatterns = [
    path('', views.index, name='index'),
    path('create_matkul', views.create_course, name="create_course"),
    path('<int:id>', views.course_detail, name="course_detail"),
    path('view-matkul/<int:id>/delete', views.delete_course, name="delete_course"),
    
]

story_6/urls.py
from django.urls import path
from . import views

app_name = 'story_6'

urlpatterns = [
    path('', views.index, name="index"),
    path('register/', views.register, name="register")
]

story_7/urls.py
from django.urls import path
from . import views

app_name = 'story_7'

urlpatterns = [
    path('', views.index, name="index"),
]

story_8/urls.py
from django.urls import path
from . import views

app_name = 'story_8'

urlpatterns = [
    path('', views.index, name="index"),
    path('api', views.search, name="api"),
]

story_9/urls.py
from django.urls import path
from . import views

app_name = 'story_9'

urlpatterns = [
    path('', views.index, name="index"),
]

home/models.py
from django.db import models

# Create your models here.

story_1/models.py
from django.db import models

# Create your models here.

story_4/models.py
from django.db import models

# Create your models here.

story_5/models.py
from django.db import models

# Create your models here.

class Semester(models.Model):
    term_choices = [
        ('Ganjil','Ganjil'),
        ('Genap','Genap')
    ]
    term_choices = models.CharField(max_length=6, choices=term_choices, default= 'Ganjil')
    year = models.CharField(max_length=9)

    def __str__(self):
        return f'{self.year} {self.term_choices}'

class MataKuliah(models.Model):
    nama = models.CharField(max_length=100)
    sks = models.PositiveSmallIntegerField()
    dosen = models.CharField(max_length=100)
    kelas = models.CharField(max_length=50)
    semester = models.ForeignKey("Semester", on_delete=models.CASCADE)
    deskripsi = models.TextField()

    def __str__(self):
        return self.nama

story_6/models.py
from django.db import models


class Activities(models.Model):
    activities_name = models.CharField(max_length=100)
    def __str__(self):
        return self.activities_name


class People(models.Model):
    people_name = models.CharField(max_length=100)
    activities = models.ForeignKey(Activities, on_delete=models.CASCADE)
    def __str__(self):
        return self.people_name

story_5/forms.py
from django.db.models import fields
from django.forms import ModelForm
from .models import MataKuliah

# Form Class
class MataKuliahForm(ModelForm):
    class Meta:
        model = MataKuliah
        fields = ['nama','sks','dosen','kelas','semester','deskripsi']

story_6/forms.py
from django.db.models import fields
from django.forms import ModelForm
from .models import People


class PeopleForm(ModelForm):
    class Meta:
        model = People
        fields = ['people_name', 'activities']

story_9/forms.py
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm

class CreateUserForm(UserCreationForm):
    def __init__(self, *args, **kwargs):
        super(CreateUserForm, self).__init__(*args, **kwargs)

        for fieldname in ['username', 'password1', 'password2']:
            self.fields[fieldname].help_text = None

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

home/views.py
from django.shortcuts import render

def index(request):
    return render(request,"home/index.html")

story_1/views.py
from django.http import response
from django.shortcuts import render

# Create your views here.


def index(request):
    return render(request,"story_1/index.html")

story_4/views.py
from django.shortcuts import render

# Create your views here.


def index(request):
    return render(request, "story_4/index.html")


def contact(request):
    return render(request, "story_4/contact.html")

story_5/views.py
from django.http import request
from django.shortcuts import redirect, render
from .forms import MataKuliahForm
from .models import MataKuliah

# Create your views here.


def index(request):
    mata_kuliah = MataKuliah.objects.all()
    context = {'page_title': 'Story 5', 'mata_kuliah': mata_kuliah}
    return render(request, "story_5/index.html", context)


def create_course(request):
    form = MataKuliahForm(request.POST or None)
    if (form.is_valid() and request.method == 'POST'):
        form.save()
        return redirect('story_5:index')
    context = {'page_title': "Create Course", 'form': form}
    return render(request, 'story_5/create_course.html', context)


def course_detail(request, id):
    mata_kuliah = MataKuliah.objects.get(id=id)
    context = {'page_title': mata_kuliah.nama, 'mata_kuliah': mata_kuliah}
    return render(request, 'story_5/course_detail.html', context)


def delete_course(request, id):
    mata_kuliah = MataKuliah.objects.get(id=id)
    mata_kuliah.delete()
    return redirect('story_5:index')

story_6/views.py
from django.http import request
from django.shortcuts import redirect, render
from .forms import PeopleForm
from .models import People, Activities


def index(request):
    people = People.objects.all()
    activities = Activities.objects.all()
    context = {'people': people, 'activities': activities, 'page_title' : 'Activities'}
    return render(request, 'story_6/index.html', context)


def register(request):
    form = PeopleForm(request.POST or None)
    if (form.is_valid() and request.method == 'POST'):
        form.save()
        return redirect('story_6:index')
    context = {'page_title': 'register', 'form':form}
    return render(request, "story_6/register.html", context)

story_7/views.py
from django.http import request
from django.shortcuts import render


def index(request):
    context = {'page_title' : 'Activities'}
    return render(request, 'story_7/index.html', context)

story_8/views.py
from django.http import JsonResponse
from django.http import response
from django.shortcuts import render
import urllib3
from json import loads


def index(request):
    context = {'page_title': 'API'}
    return render(request, 'story_8/index.html', context)


def search(request):
    http = urllib3.PoolManager()
    response = http.request(
        'GET', "https://www.googleapis.com/books/v1/volumes?" +request.GET.urlencode())
    context = loads(response.data.decode('utf-8'))

    return JsonResponse(context)

story_9/views.py
from django.http import response
from django.shortcuts import render, redirect
from .forms import CreateUserForm
from django.contrib.auth import authenticate, login


def index(request):
    form = CreateUserForm()
    message = "Create your account"
    if request.method == "POST":
        form = CreateUserForm(request.POST)
        if form.is_valid():
            form.save()
            user = authenticate(username=form.cleaned_data.get("username"),
            password=form.cleaned_data.get("password1"))
            login(request, user)
        else:
            message = "⚠️failed to create account"
            form = CreateUserForm()
    context = {'page_title': 'Login', 'form' : form, 'message':message}
    return render(request, 'story_9/index.html', context)

story_1/templates/story_1/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <meta http-equiv="X-UA-Compatible" content="ie=edge" />
  <link rel="stylesheet" href="{% static 'story_1/style.css' %}" />
  <link rel="stylesheet" href="{% static 'home/nav.css' %}" />
  <link href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@300&display=swap" rel="stylesheet" />
  <title>Story 1</title>
</head>

<body>
  {% include "home/nav.html" %}
  <div>
    <h1>Profile</h1>
  </div>
  <div class="flex-grid">
    <div class="col">
      <div class="desc">
        <p>Nama: Mustafa Zaki Assagaf</p>
        <p>MPM: 1906398824</p>
        <p>Angkatan: 2019</p>
        <p>Hobi: Belajar</p>
        <p>Deskripsi: yes</p>
        <p>Kukiah: Universitas Isekai</p>
        <p>Pendidikan: yes</p>
        <p>Medsos</p>
      </div>
    </div>
    <div class="col">
      <a href="google.com"> <img class="img-box" src="{% static 'story_1/foto.jpg' %}" /></a>
    </div>
  </div>
</body>

</html>

story_4/templates/story_4/contact.html
{% load static %}
<!DOCTYPE html>
<html>

{% include 'story_4/head.html' %}

<body>
  {% include 'story_4/navbar.html' %}
  <div id="contact" id="contact">
    <div class="content">
      <div class="grid">
        <div class="child align-center">
          <img class="logo" src="{% static 'story_4/Insta.png' %}" />
          <p>mustafa.segf</p>
        </div>
        <div class="child align-center">
          <img class="logo" src="{% static 'story_4/Line.png' %}" />
          <p>mustafa.segf</p>
        </div>
        <div class="child align-center">
          <img class="logo" src="{% static 'story_4/Github.png' %}" />
          <p>mustafasegf</p>
        </div>
        <div class="child align-center">
          <img class="logo" src="{% static 'story_4/Linkedin.png' %}" />
          <p>mustafa zaki assagaf</p>
        </div>
      </div>
    </div>
  </div>
</body>

</html>

story_4/templates/story_4/head.html
{% load static %}
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <title>Story 3</title>
  <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@200;300;400;500;600;700&display=swap"
    rel="stylesheet" />
  <link rel="stylesheet" href="{% static 'story_4/style.css' %}" />
</head>

story_4/templates/story_4/index.html
{% load static %}
<!DOCTYPE html>
<html>
  
{% include 'story_4/head.html' %}
<link rel="stylesheet" href="{% static 'home/nav.css' %}" />

<body>
  {% include "home/nav.html" %}
  <div id="hero-section">
    <div class="content">
      <div class="grid">
        <div class="child">
          <p>THIS IS ME</p>
          <h1>MUSTAFA ZAKI ASSAGAF</h1>
          <p>
            Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor
            incididunt ut labore et dolore magna aliqua. Ut enim ad minim
          </p>
          <a href="{% url 'story_4:contact' %}" class="btn">CONTACT ME</a>
        </div class="child">
        <div>
          <img class="hero-img" src="{% static 'story_4/pict.png' %}" />
        </div>
      </div>
    </div>
  </div>

  <div id="about">
    <div class="content">
      <div class="align-center">
        <p>ABOUT ME</p>
        <h3>PERSONAL DETAIL</h3>
        <p>
          Generic as shit Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed
          do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad
          minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea
          commodo consequat. Duis aute irure dolor in reprehenderit in voluptate
        </p>
        <a href="" class="btn">CHECK MY CV</a>
      </div>
    </div>
  </div>

  <div id="skills">
    <div class="content">
      <div class="align-center space">
        <h3>ABOUT ME</h3>
        <p>basic ass description about my skill. May exagerate a bit.. or alot i don’t know. Depends on
          my mood</p>
      </div>
      <div class="grid">
        <div class="child align-center">
          <img class="logo" src="{% static 'story_4/python.png' %}" />
          <h5>Python</h5>
          <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut
            labore et dolore magna aliqua.</p>
        </div>
        <div class="child align-center">
          <img class="logo" src="{% static 'story_4/javascript.png' %}" />
          <h5>Javascript</h5>
          <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut
            labore et dolore magna aliqua.</p>
        </div>
        <div class="child align-center">
          <img class="logo" src="{% static 'story_4/react.png' %}" />
          <h5>React</h5>
          <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut
            labore et dolore magna aliqua.</p>
        </div>
        <div class="child align-center">
          <img class="logo" src="{% static 'story_4/nodejs.png' %}" />
          <h5>NodeJS</h5>
          <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut
            labore et dolore magna aliqua.</p>
        </div>

      </div>

    </div>
  </div>
  <div id="experience">
    <div class="content">
      <div class="align-center space">
        <h3>EXPERIENCE</h3>
        <p>Well i don’t have any professional experience but hey i’m pretty active on my uni, so this is my
          organizational experience</p>
      </div>
      <div class="grid">
        <div class="child">
          <img class="logo" src="{% static 'story_4/betis.png' %}" />
          <h5>BETIS</h5>
          <p>December 2019 - juni 2020</p>
        </div>
        <div class="child">
          <img class="logo" src="{% static 'story_4/sistem.png' %}" />
          <h5>SISTEM</h5>
          <p>Februari 2020 - Sekarang</p>
        </div>
        <div class="child">
          <img class="logo" src="{% static 'story_4/compfest.png' %}" />
          <h5>COMPFEST</h5>
          <p> Maret 2020 - Sekarang</p>
        </div>

        <div class="child">
          <img class="logo" src="{% static 'story_4/pmb.png' %}" />
          <h5>PMB</h5>
          <p>Agustus 2020 - Sekarang</p>
        </div>

        <div class="child">
          <img class="logo" src="{% static 'story_4/DDP0.png' %}" />
          <h5>DDP0</h5>
          <p>july 2020 - september 2020</p>
        </div>

      </div>
    </div>
  </div>
  <div id="contact" id="contact">
    <div class="content">
      <div class="grid">
        <div class="child align-center">
          <img class="logo" src="{% static 'story_4/Insta.png' %}" />
          <p>mustafa.segf</p>
        </div>
        <div class="child align-center">
          <img class="logo" src="{% static 'story_4/Line.png' %}" />
          <p>mustafa.segf</p>
        </div>
        <div class="child align-center">
          <img class="logo" src="{% static 'story_4/Github.png' %}" />
          <p>mustafasegf</p>
        </div>
        <div class="child align-center">
          <img class="logo" src="{% static 'story_4/Linkedin.png' %}" />
          <p>mustafa zaki assagaf</p>
        </div>
      </div>
    </div>
  </div>
  <div class="footer"></div>
</body>

</html>

story_4/templates/story_4/navbar.html
{% load static %}
<div id="navbar">
  <div class="nav-grid">
    <a href="{% url 'story_4:index' %}">
      <h5>MUSTAFA</h5>
    </a>
    <a href="{% url 'story_4:index' %}#hero-dection">HOME</a>
    <a href="{% url 'story_4:index' %}#about">ABOUT</a>
    <a href="{% url 'story_4:index' %}#skills">SKILLS</a>
    <a href="{% url 'story_4:index' %}#experience">EXPERIENCE</a>
    <a href="{% url 'story_4:contact' %}">CONTACT</a>
  </div>
</div>